version: '3.8'

services:
  river-permit-bot:
    build: .
    container_name: river-permit-bot
    restart: always
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - DATA_DIR=/app/data
      - PYTHONUNBUFFERED=1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"